In [2]:
import numpy as np
from numpy import matlib

In [3]:
#create array
arr = [1, 2, 3, 4]
nparr = np.array(arr)

In [4]:
npmat = np.matrix(arr)
print(nparr)
print(npmat)

[1 2 3 4]
[[1 2 3 4]]


In [5]:
#indexing works through comma separation
npmat[0, 1]

2

In [6]:
#reshape reshapes the matrix into dimensions, ensures dimensions line up

npmat.reshape(2,2)[0,1]

#.T takes the transpose
print(npmat.T)

[[1]
 [2]
 [3]
 [4]]


In [7]:
npmat.reshape(npmat.shape[1], npmat.shape[0])
#equivalent to transpose
#npmat.shape reshapes the matrix

matrix([[1],
        [2],
        [3],
        [4]])

In [8]:
npmat + npmat #addition is element wise

matrix([[2, 4, 6, 8]])

In [9]:
#npmat * npmat #multipilcation is matrix multipication
npmat * npmat.T

matrix([[30]])

In [10]:
 npmat.T * npmat #npmatricies act as row matrices, each sub list is a row in the overall matrix

matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

In [11]:
np.multiply(npmat, npmat) #multiplies matrices element wise, equivalent to .* in Matlab

matrix([[ 1,  4,  9, 16]])

In [12]:
npmat * 3
3 * npmat

matrix([[ 3,  6,  9, 12]])

In [13]:
npmat ** 2 #only works for square arrayss

ValueError: input must be a square array

In [14]:
(npmat.T * npmat)**2

matrix([[ 30,  60,  90, 120],
        [ 60, 120, 180, 240],
        [ 90, 180, 270, 360],
        [120, 240, 360, 480]])

In [15]:
np.exp(npmat) #exponential

matrix([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003]])

In [16]:
np.power(npmat, 3) #power function

matrix([[ 1,  8, 27, 64]])

In [17]:
np.sin(npmat) #takes sin

matrix([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]])

In [18]:
1/npmat #division is done element wise

matrix([[ 1.        ,  0.5       ,  0.33333333,  0.25      ]])

In [19]:
1 / (1 + np.exp(-1 * npmat)) #logistic function

matrix([[ 0.73105858,  0.88079708,  0.95257413,  0.98201379]])

In [20]:
npmat + 1 #adds 1 to all elements

matrix([[2, 3, 4, 5]])

In [21]:
npmat2 = np.matrix([[1, 2, 3], [3, 4, 6], [6,2, 1]])

In [22]:
np.linalg.det(npmat2) #determinant
np.linalg.matrix_rank(npmat) #rank of matrix
np.linalg.svd(npmat)
np.linalg.svd(npmat2) #array represents singular values (would be in regular matrix shape) #first matrix is U and second is V, middle are singular values in the sigma matrix

(matrix([[-0.35502281, -0.30689994, -0.88304656],
         [-0.77069113, -0.43856474,  0.46227282],
         [-0.52914459,  0.84467354, -0.08082458]]),
 array([ 9.81476961,  4.43416845,  0.09191104]),
 matrix([[-0.59522168, -0.49426522, -0.63357165],
         [ 0.77702215, -0.15306404, -0.61058003],
         [ 0.20481144, -0.85572968,  0.47516206]]))

In [23]:
np.ones(5) #array of ones
np.matlib.ones((4, 3)) #matrix of ones (takes in a tuple)


matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [24]:
np.zeros(4)
np.matlib.zeros((3, 4))

matrix([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])

In [26]:
np.matlib.random.random((2, 3)) #random matirx
np.matlib.random.rand(2, 3, 4)
np.matlib.random.randn(2, 3) #normal distribution


array([[ 0.63416846,  0.4438996 ,  0.54133354],
       [ 0.23834852,  0.92288728,  0.71204975]])

In [130]:
np.hstack((npmat2, np.matrix([1, 1, 1]).T)) #adding columns/rows to matrices
np.vstack((npmat2, np.matrix([1, 1, 1])))

matrix([[1, 2, 3],
        [3, 4, 6],
        [6, 2, 1],
        [1, 1, 1]])

ValueError: matrix must be 2-dimensional

In [30]:
s = np.matrix([[4.0, 3.0, 2.0], [3.0, 4.0, 2.0], [1.0, 9.0, 4.0]])

In [47]:
k = np.matrix(np.random.random((4, 4)))
l = np.matrix(np.zeros((2, 3)))
l = np.array(np.ndarray.flatten(s))[0]
(5, 4)
np.array(k)

array([[ 0.34179219,  0.73767254,  0.79311478,  0.63607406]])

In [246]:
def sigmoid(x):
    return 1/ (1 + np.exp(-1 * x))

In [256]:
print(s)
def apply_func_to_matrix(s, func):
    for i in range(s.shape[0]):
        for j in range(s.shape[1]):
            s[i, j] = func(float(s[i, j]))
    return s

print(apply_func_to_matrix(s, lambda x: np.exp(-1 * float(x))))



[[ 4.          3.          2.        ]
 [ 3.          0.98201379  2.        ]
 [ 1.          9.          4.        ]]
[[  1.83156389e-02   4.97870684e-02   1.35335283e-01]
 [  4.97870684e-02   3.74556062e-01   1.35335283e-01]
 [  3.67879441e-01   1.23409804e-04   1.83156389e-02]]


In [254]:
s[1, 1] = 1/ (1+ np.exp(-1* s[1,1]))

In [255]:
print(s[1, 1])

0.982013790038
